### ISSUE TITLE
https://www.freecodecamp.com/email-submit returns a 404 error

### ISSUE THREAD

**Issue by JoshuaAdrianJones** [danilo-p/freecodecamp-landing-challenge#1]
when coding the submit button functionality the requirement is a form action to https://www.freecodecamp.com/email-submit but this url returns a 404 error on the FCC website

**Comment by danilo-p** [comment]
Hello @JoshuaAdrianJones. This is a personal repository created by me for an exercise at the FCC platform. I believe you intended to post this comment in some official freeCodeCamp repository. Please, reach out to them instead. I'm closing the issue as I can't help you.
